// Copyright (C) 2025-2026 PagePerfect(TM) Group. All Rights Reserved.
// The PagePerfect(TM) Content Editor is licensed under the MIT License.
// However this website and its source code are NOT.
// Contact us at https://pageperfect.pages.dev/help/form
// for a customized verion of PagePerfect(TM) for your company.

// Build the PagePerfect(TM) Content Editor (the core component of PagePerfect(TM))
const editor=new PagePerfect('#editor',{height:400,toolbarSticky:false,buttons:"find,undo,redo,print,spellcheck,copyformat,eraser,about, |,paragraph, |,font, |,fontsize, |,bold,italic,underline,strikethrough,brush, |,cut,copy,paste,selectall, |,hr,fullsize |,link,image,video,file,table,symbols |,align,lineHeight,ul,ol, |,indent,outdent, |,superscript,subscript, |,source,preview",spellcheck:true});

// Creates the template HTML on export
function buildHTML(content){return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="generator" content="PagePerfect 26"><title>Untitled Page | PagePerfect 26</title><link rel="shortcut icon" href="https://pageperfect.pages.dev/branding/favicon.png" type="image/x-icon"><link rel="stylesheet" type="text/css" href="https://pageperfect.pages.dev/global.css"></head>\n<body><main class="content-container">${content}</main></body></html>`;}

// The PagePerfect(TM) Project (p^3)/.p3 file format is the current PROPRIETARY format for PagePerfect(TM)
function extractContentFromHTML(html) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');

    // Verify the file was generated by a PagePerfect(TM) version
    const generator = doc.querySelector('meta[name="generator"]');
    if (!generator || !generator.content.includes('PagePerfect')) {
        throw new Error('Not a valid PagePerfect project file.');
    }

    const main = doc.querySelector('main.content-container');
    if (!main) {
        throw new Error('Invalid PagePerfect file structure.');
    }

    return main.innerHTML;
}

// Save the .p3 file (see 'downloadBtn' for HTML code)
document.getElementById('saveBtn').addEventListener('click', function () {
    const content = editor.value;

    if (!content) {
        alert('FAILURE: Your page is empty.');
        return;
    }

    const blob = new Blob(
        [buildHTML(content)],
        { type: 'application/x-pageperfect-project' }
    );

    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = 'untitled_project.p3';

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
});

// Open a .p3 file. The PagePerfect(TM) Content Editor does not allow users
// to open HTML files in order to protect their work and make sure the editor
// does not break
document.getElementById('openBtn').addEventListener('click', function () {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.p3';

    input.addEventListener('change', function () {
        const file = input.files[0];
        if (!file) return;

        if (!file.name.toLowerCase().endsWith('.p3')) {
            alert('FAILURE: Only .p3 PagePerfect project files are supported.');
            return;
        }

        const reader = new FileReader();
        reader.onload = function (e) {
            try {
                const html = e.target.result;
                const content = extractContentFromHTML(html);

                editor.value = content;
            } catch (err) {
                alert(
                    'FAILURE: This file is not a valid PagePerfect project.\n\n' +
                    'DETAILS: ' + err.message
                );
            }
        };

        reader.readAsText(file);
    });

    input.click();
});

// Save the HTML code (see 'saveBtn' for .p3 file)
document.getElementById('downloadBtn').addEventListener('click', function () {
    const content = editor.value;

    if (!content) {
        alert('FAILURE: Your page is empty.');
        return;
    }

    const blob = new Blob([buildHTML(content)], { type: 'text/html' });
    const link = document.createElement('a');

    link.href = URL.createObjectURL(blob);
    link.download = 'untitled_page.html';

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
});

// Copy the HTML to the user's clipboard
document.getElementById('copyBtn').addEventListener('click', async function () {
    const content = editor.value;

    if (!content) {
        alert('FAILURE: Your page is empty.');
        return;
    }

    try {
        await navigator.clipboard.writeText(buildHTML(content));
        alert('SUCCESS: The content has been copied to your clipboard.');
    } catch (err) {
        alert('FAILURE: The content was not copied to your clipboard.\n\nSUGGESTION: Ensure PagePerfect has permission to access your clipboard.');
        console.error(err);
    }
});

// Old clearBtn logic
// document.getElementById('clearBtn').addEventListener('click',function(){editor.value='';});

// Clear the PagePerfect(TM) Content Editor
document.getElementById('clearBtn').addEventListener('click', function () {
    const content = editor.value;

    if (!content) {
        return;
    }

    const confirmed = confirm(
        'WARNING: Are you sure you want to clear this page? This action cannot be undone.\n\nNOTICE: All of your content will be erased.'
    );

    if (confirmed) {
        editor.value = '';
    }
});

// Open the PagePerfect(TM) help documentation
document.getElementById('helpBtn').addEventListener('click',function(){window.open("https://pageperfect.pages.dev/help/");})

// Prevent users from losing unsaved progress
window.addEventListener('beforeunload',function(e){const content=editor.value;if(content){e.preventDefault();}});
